# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import lsdslam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to=lsdslam.models.content_file_name)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
